$id: http://freenas.org/zettarepl/schema.json
$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  periodic-snapshot-tasks:
    type: array
    items:
      $ref: http://freenas.org/zettarepl/periodic-snapshot-task.schema.json
  replication-tasks:
    type: array
    items:
      $ref: http://freenas.org/zettarepl/replication-task.schema.json
  timezone:
    type: string
